---
# vi: :shiftwidth=2:nu:ai:set tabstop=2:softtabstop=2:expandtab

- hosts: all
  vars:
    ini_true: true
    ini_false: false
    TODO_Section: Midnight-Commander
    ini:
      mcview_remember_file_position: 1
      auto_save_setup_panels: 1
      use_internal_view: 0
      use_internal_edit: 0
      confirm_delete: 0
      confirm_exit: 0

  tasks:
   - name: check if ini exist
     stat: path=~/.config/mc/ini
     register: mc_ini

   - name: notify if ini absent
     when: mc_ini.stat.exists == False
     debug: msg="you'd forget to run mc your very first time" 

   - name: tune mc and be god
     when: mc_ini.stat.exists == True
     ini_file: dest=~/.config/mc/ini
               section={{ TODO_Section }}
               option={{ item.key }}
               value={{ item.value }}
     with_dict: "{{ ini }}"

